spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testbook03?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root@123
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待时间
    maxWait: 60000
    #打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL 记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableldleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy